// WAREHOUSE
export const WAREHOUSE_TRANSFER_KEY = 'WAREHOUSE_KEY'
export const WAREHOUSE_KEY = 'WAREHOUSE_KEY'

// STAFF
export const STAFF_KEY = 'STAFF_KEY'

// STATISTICAL
export const DISCOUNT_REPORT_KEY = 'DISCOUNT_REPORT_KEY'

export const REAL_SALES_KEY = 'REAL_SALES_KEY'
